# Generated by Django 3.0.6 on 2020-05-17 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField()),
                ('detail', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='detail',
            field=models.TextField(max_length=500),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(max_length=500)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.ItemDraft')),
            ],
        ),
        migrations.AddField(
            model_name='itemdraft',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item'),
        ),
    ]
