# Generated by Django 3.0.3 on 2020-05-22 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20200519_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftfile',
            name='detail',
        ),
        migrations.AddField(
            model_name='draftfile',
            name='mp_lyrics',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
